### ISSUE TITLE
Make Webpack Plugin for UIkit Custom Icons

### ISSUE THREAD

**Issue by aarongerig** [w-vision/Wvision#38]
Enhancement for workflow / deployment.

https://github.com/uikit/uikit/blob/develop/build/icons.js

**Comment by aarongerig** [comment]
What would be the benefit of a UIkit webpack plugin?

**Comment by dpfaffenbauer** [comment]
Somit muss nicht während des deployment Prozesses das NPM install im uikit Ordner ausgeführt werden und die custom-icons dort generiert werden. Der Vorteil darin liegt im erhöhen der Performance für deployment und des ausmerzen des doppelten installieren von NPM Abhängigkeiten.

**Comment by aarongerig** [comment]
Momentan muss ich dies leider immer machen, damit ich die einzelnen UIkit Komponenten modular laden kann (reducing size). Mit dem nächsten UIkit release, sollte es möglich sein, die Komponenten direkt von den Source files zu laden. Abwarten und Tee trinken ... :)

**Comment by dpfaffenbauer** [comment]
alright 👍

**Comment by aarongerig** [comment]
Not necessary anymore.
